version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: ./compose/Dockerfile
    container_name: pi_api
    # command: sh -c ". venv/bin/activate && flask run --host=0.0.0.0"
    command: flask run --debug --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development